// apps/web/eslint.config.mjs
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import a11y from 'eslint-plugin-jsx-a11y';
import importPlugin from 'eslint-plugin-import';
import nextPlugin from '@next/eslint-plugin-next';
import globals from 'globals';

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': a11y,
      import: importPlugin,
      '@next/next': nextPlugin,
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...a11y.configs.recommended.rules,
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      'import/order': ['warn', { 'newlines-between': 'always', alphabetize: { order: 'asc' } }],
    },
    settings: { react: { version: 'detect' } },
  },
  {
    files: ['scripts/**/*.{ts,js}', '**/*.config.{ts,mjs,js}'],
    rules: { 'no-console': 'off' },
  },
  {
    // 1.6 features hebben skeleton-forms zonder volledige a11y-coupling
    // (label htmlFor + keyboard-handlers op clickable rows). Deferred-work
    // entry A11Y-1.6-PASS dekt de inhaalslag in Fase 1.7 / pre-prod.
    files: [
      'features/leave/**',
      'features/sick/**',
      'features/expenses/**',
      'features/contracts/**',
      'features/bonus/**',
      'features/care-package/**',
      'features/statements/**',
      'features/profile/**',
      'features/broadcasts/**',
      'features/dashboard/**',
      'features/notifications/employee/**',
      'features/payslips/**',
      'features/assignments/**',
      'features/employees/**',
      'features/projects/**',
      'features/clients/**',
      'app/(authed)/**',
      'app/(admin)/admin/**',
    ],
    rules: {
      'jsx-a11y/label-has-associated-control': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
    },
  },
  {
    // next-env.d.ts is auto-generated by Next.js and must not be edited
    // (https://nextjs.org/docs/app/api-reference/config/typescript)
    ignores: ['.next/**', 'node_modules/**', 'dist/**', 'e2e/**', 'next-env.d.ts'],
  },
];
